# Generated by Django 3.1.6 on 2021-04-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('network', models.CharField(max_length=80)),
                ('release_date', models.DateTimeField()),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
    ]
